// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int32            `db:"id" json:"id"`
	UserID    int32            `db:"user_id" json:"user_id"`
	Currency  string           `db:"currency" json:"currency"`
	Balance   pgtype.Numeric   `db:"balance" json:"balance"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Transfer struct {
	ID            int32            `db:"id" json:"id"`
	FromAccountID int32            `db:"from_account_id" json:"from_account_id"`
	ToAccountID   int32            `db:"to_account_id" json:"to_account_id"`
	Amount        pgtype.Numeric   `db:"amount" json:"amount"`
	Description   pgtype.Text      `db:"description" json:"description"`
	Status        pgtype.Text      `db:"status" json:"status"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type User struct {
	ID               int32            `db:"id" json:"id"`
	Email            string           `db:"email" json:"email"`
	PasswordHash     string           `db:"password_hash" json:"password_hash"`
	FirstName        string           `db:"first_name" json:"first_name"`
	LastName         string           `db:"last_name" json:"last_name"`
	WelcomeEmailSent pgtype.Bool      `db:"welcome_email_sent" json:"welcome_email_sent"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
