// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	AddToBalance(ctx context.Context, arg AddToBalanceParams) (Account, error)
	CountTransfersByAccount(ctx context.Context, fromAccountID int32) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAccount(ctx context.Context, id int32) (Account, error)
	GetAccountByUserAndCurrency(ctx context.Context, arg GetAccountByUserAndCurrencyParams) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int32) (Account, error)
	GetAccountsWithBalance(ctx context.Context) ([]Account, error)
	GetTransfer(ctx context.Context, id int32) (GetTransferRow, error)
	GetTransfersByAccount(ctx context.Context, arg GetTransfersByAccountParams) ([]GetTransfersByAccountRow, error)
	GetTransfersByDateRange(ctx context.Context, arg GetTransfersByDateRangeParams) ([]GetTransfersByDateRangeRow, error)
	GetTransfersByStatus(ctx context.Context, arg GetTransfersByStatusParams) ([]GetTransfersByStatusRow, error)
	GetTransfersByUser(ctx context.Context, arg GetTransfersByUserParams) ([]GetTransfersByUserRow, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserAccounts(ctx context.Context, userID int32) ([]Account, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]ListTransfersRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkWelcomeEmailSent(ctx context.Context, id int32) error
	SubtractFromBalance(ctx context.Context, arg SubtractFromBalanceParams) (Account, error)
	UpdateAccount(ctx context.Context, id int32) (Account, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) (Transfer, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
